let shopItemsData = [
  {
    id: "producto1",
    name: "Niza",
    price: 45,
    desc: "Sumérgete en un mundo de sonido envolvente con nuestros auriculares de alta calidad.<br><tittle>Disfruta de una experiencia auditiva única y vívida mientras te sumerges en tu música favorita.‌</tittle><br><br>",
    img: "img/casco1.jpg",
  },
  {
    id: "producto2",
    name: "Sidney",
    price: 100,
    desc: "Vive la música con una calidad de sonido excepcional gracias a nuestros auriculares de última generación.<br><tittle>Cada nota, cada detalle, se reproduce con una claridad impresionante, transportándote a una nueva dimensión musical.‌</tittle>",
    img: "img/casco2.jpg",
  },
  {
    id: "producto3",
    name: "Dubrovnik",
    price: 25,
    desc: "Experimenta la comodidad y el estilo con nuestroe elegantes auriculares.<tittle> Diseñados con materiales de alta calidad y un ajuste perfecto,te brindan horas de uso sin molestia.‌</tittle><br><br><br>",
    img: "img/casco3.jpg",
  },
  {
    id: "producto4",
    name: "Miami",
    price: 300,
    desc: "Descubre la libertad de movimiento con nuestros auriculares inalámbricos.<br><tittle>Olvídate de los cables y disfruta de la música sin restricciones, ya sea en casa, en el gimnasio o en la calle.‌</tittle><br><br>",
    img: "img/casco4.jpg",
  },
  {
    id: "producto5",
    name: "Cancún",
    price: 25,
    desc: "Potencia tus entrenamientos con nuestros auriculares deportivos.<br>‌<tittle>Diseñados para resistir el sudor y los movimientos intensos, te brindan un sonido excepcional mientras te mantienes activo.‌‌</tittle>",
    img: "img/casco5.jpg",
  },
  {
    id: "producto6",
    name: "Bali",
    price: 200,
    desc: "Disfruta de la inmersión en tus juegos favoritos con nuestros auriculares para gaming.<br><tittle>Escucha cada detalle y cada paso con una claridad impresionante, dándote una ventaja competitiva en cada partida.‌</tittle>",
    img: "img/casco6.jpg",
  },
  {
    id: "producto7",
    name: "Callao",
    price: 450,
    desc: "Haz que tus llamadas sean claras y nítidas con nuestros auriculares con micrófono integrado.<tittle><br>Ya sea para reuniones de trabajo o llamadas con amigos, nunca te perderás una palabra.</tittle>",
    img: "img/casco7.jpg",
  },
  {
    id: "producto8",
    name: "Marbella",
    price: 45,
    desc: "Experimenta un sonido envolvente en tus películas y series favoritas con nuestros auriculares para home theater.<br><tittle>Cada explosión, cada diálogo, se reproduce con una calidad de cine en la comodidad de tu hogar.</tittle>",
    img: "img/casco8.jpg",
  },
  {
    id: "producto9",
    name: "Honolulu",
    price: 85,
    desc: "Eleva tu experiencia musical con nuestros auriculares de alta fidelidad. <tittle>Diseñados para audiófilos exigentes, te brindan un sonido puro y sin compromisos, permitiéndote disfrutar de la música como nunca antes.</tittle>",
    img: "img/casco9.jpg",
  },

];
